PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.12.7"

inputs:
- name: gpupgrade_src
  path: go/src/github.com/greenplum-db/gpupgrade

caches:
- path: go/pkg/dep

params:
  DEPCACHEAGE: 24h

run:
  path: go/src/github.com/greenplum-db/gpupgrade/ci/scripts/gen-go-dep-cache.bash

outputs:
- name: go/pkg
- name: go/bin
